# -*- coding: utf-8 -*-
"""Teste Python - VICTOR PATRICIO MANAIA.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Xj2f9pcbUQRlVXjYbvYY3vL6EflqALdp
"""

"EXERCÍCIO 1"
num=0
cont=0
list=[]
while num in range(0,5000000):
  num=num+1
  if num%2==0 and num%37==0 and num%49==0:
    cont=cont+1
    list.append([num])

print(f'O total de números no intervalo de 1 a 5 milhões, pares, múltiplos de 49 e múltiplos de 37 são: {cont}')
print(f'Os números são: {list}')

"EXERCÍCIO 2"
import numpy as np
import math
a =0
i=0
vetorx=np.array([])
lista =[]
while a<11:
  if i%2==0:
    n = ((math.pow(3,i)+(7*(math.factorial(i)))))
    x = float(np.append(vetorx,n))
    print(f'O valor deste vetor é: {x:.2f}. Sua posição é a {i}º')
    a=a+1
    i=i+1
  else:
    m = math.pow(2,i)+4*math.log(i)
    y = float(np.append(vetorx,m))
    print(f'O valor deste vetor é: {y:.2f}. Sua posição é a {i}º')
    a=a+1
    i=i+1
media = x+y/10
print(f'Essa é a média: {media}')
print('O maior valor está na 10º posição')

"EXERCÍCIO 3"
from random import randint
lista10=[]
cont10=0
for i in range (1,6):
  x10=randint(1,10)
  print(f'O aluno {i} obteve nota: {x10}')
  lista10.append(x10)
print(lista10)
maximo=max(lista10)
for con in range(1,5):
  lista10[con]
  if lista10[con]==maximo:
    print(f'A maior nota corresponde ao aluno {con+1} que obteve a nota {maximo}')